version: "3.8"

services:
  webapp:
    build: .
    container_name: myaspnetapp
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    env_file:
          - ./.env
    volumes:
      - ./wwwroot/img:/app/wwwroot/img
    networks:
      - alittleleaf-network
    depends_on:
      db:
        condition: service_healthy # Đợi cho đến khi db "khỏe mạnh"

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${MSSQL_SA_PASSWORD}
    volumes:
      - mssqldata:/var/opt/mssql
      - ./SQL:/docker-entrypoint-initdb.d
    networks:
      - alittleleaf-network
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "${MSSQL_SA_PASSWORD}", "-C", "-Q", "select 1"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

volumes:
  mssqldata:
  
networks:
  alittleleaf-network:
    driver: bridge